FROM node:20-slim

LABEL maintainer="Antoniel"
LABEL email="antoniel@email.com"
LABEL version="1.0.0"

RUN apt update -y && \
  apt install --no-install-recommends -y \
  openssl && \
  rm -rf /var/lib/apt/lists/*

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node package*.json ./

RUN npm install && npm cache clean --force

COPY --chown=node:node . .

EXPOSE 3000

CMD ["npm","run","start:prod"]